### ISSUE TITLE
Does not work on Ubuntu 16.04 PC

### ISSUE THREAD

**Issue by xtcuser** [twelvesec/gasmask#47]
I am using **Ubuntu 16.04 LTS**, **64bit**.
While using **Python 3.5.2**
```
closx@closx-pc:~/tools/data/gasmask$ python gasmask.py
  File "gasmask.py", line 122
    print ip.ljust(16) + \
           ^
SyntaxError: invalid syntax
```
While using **Python 2**
```
closx@closx-pc:~/tools/data/gasmask$ python2 gasmask.py
Traceback (most recent call last):
  File "gasmask.py", line 39, in <module>
    import censys.certificates
ImportError: No module named censys.certificates
```
I could not understand what is wrong.

**Comment by Meowcat285** [comment]
sudo pip install -r requirements.txt
then do python gasmask.py
