### ISSUE TITLE
ModuleNotFoundError: No module named 'censys.certificates'

### ISSUE THREAD

**Issue by bakalilinux** [twelvesec/gasmask#60]
python3 gasmask.py  
Traceback (most recent call last):
  File "/home/hacker/Downloads/gasmask/gasmask.py", line 44, in <module>
    import censys.certificates
ModuleNotFoundError: No module named 'censys.certificates'

**Comment by ITCMD** [comment]
Same issue here on Ubuntu.

Freshly cloned, then ran `sudo pip3 install -r requirement.txt`

`python gasmask.py` returns:

```
ubuntu@instance-20211031-1415:~/gasmask$ python gasmask.py
  File "gasmask.py", line 994
    url = f'https://{server}/v2/data/domain/subdomain?limit={limit}&domain={value}'
                                                                                  ^
SyntaxError: invalid syntax
```
`python3 gasmask.py` returns:

ubuntu@instance-20211031-1415:~/gasmask$
```
Traceback (most recent call last):
  File "gasmask.py", line 44, in <module>
    import censys.certificates
ModuleNotFoundError: No module named 'censys.certificates'
ubuntu@instance-20211031-1415:~/gasmask$
```

**Comment by bawed** [comment]
1.1.1版本可以

**Comment by Rickyemmermeer** [comment]
Use pipenv! Create pipenv and install all dependencies there and then run gasmask in pipenv and then it works!
